[package]
name = "ares"
version = "0.1.0"
edition = "2021"
authors = ["tims <0xtimsb@gmail.com>"]
description = "ares is tiny gui library for rust"
publish = false
license = "GPL-3.0"

[lib]
path = "src/ares.rs"

[features]
default = ["wayland"]
wayland = []

[dependencies]
wayland-client = "0.30.0"
anyhow = "1.0"
slotmap = "1.0.7"
raw-window-handle = "0.6.2"